-- 1. Create Areas table (Safety check)
create table if not exists areas (
  id bigint generated by default as identity primary key,
  name text not null,
  capacity int default 0,
  is_active boolean default true
);

-- 2. Add ResDiary columns to Dining Tables
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'dining_tables' and column_name = 'area_id') then
    alter table dining_tables add column area_id bigint references areas(id);
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'dining_tables' and column_name = 'min_covers') then
    alter table dining_tables add column min_covers int default 2;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'dining_tables' and column_name = 'max_covers') then
    alter table dining_tables add column max_covers int default 4;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'dining_tables' and column_name = 'is_combinable') then
    alter table dining_tables add column is_combinable boolean default false;
  end if;
end $$;

-- 3. Upgrade Bookings Table Logic
create table if not exists bookings (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add columns individually (Safe for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'customer_name') then
    alter table bookings add column customer_name text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'customer_phone') then
    alter table bookings add column customer_phone text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'customer_email') then
    alter table bookings add column customer_email text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'customer_tags') then
    alter table bookings add column customer_tags jsonb default '[]';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'booking_time') then
    alter table bookings add column booking_time timestamp with time zone;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'duration_minutes') then
    alter table bookings add column duration_minutes int default 90;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'turn_time_minutes') then
    alter table bookings add column turn_time_minutes int default 15;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'party_size') then
    alter table bookings add column party_size int default 2;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'status') then
    alter table bookings add column status text default 'CONFIRMED';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'booking_source') then
    alter table bookings add column booking_source text default 'WALK_IN';
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'table_id') then
    alter table bookings add column table_id bigint references dining_tables(id);
  end if;
  
  -- Special handling for standard column (Simpler and safer than generated for intervals)
  if not exists (select 1 from information_schema.columns where table_name = 'bookings' and column_name = 'expected_end_time') then
    alter table bookings 
    add column expected_end_time timestamp with time zone;
  end if;
end $$;

-- Trigger to auto-calculate expected_end_time instead of generated column
-- This bypasses the immutability restriction
create or replace function calculate_end_time()
returns trigger as $$
begin
  new.expected_end_time := new.booking_time + (new.duration_minutes || ' minutes')::interval;
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_expected_end_time on bookings;

create trigger set_expected_end_time
before insert or update of booking_time, duration_minutes on bookings
for each row
execute function calculate_end_time();

-- 4. Settings for Flow Control
create table if not exists booking_settings (
  id bigint generated by default as identity primary key,
  interval_minutes int default 15,
  max_covers_per_interval int default 20,
  default_turn_time int default 15,
  duration_rules jsonb default '{"2": 90, "4": 105, "6": 120, "10": 150}'::jsonb
);

-- 5. Waitlist
create table if not exists waitlist (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  contact_info text,
  party_size int not null,
  quoted_wait_time int,
  status text default 'WAITING'
);

-- 6. Insert default data (Idempotent)
insert into areas (name)
select 'Main Dining' where not exists (select 1 from areas where name = 'Main Dining');

insert into booking_settings (interval_minutes, max_covers_per_interval) 
select 15, 15 where not exists (select 1 from booking_settings);
