
-- Run this in Supabase SQL Editor to enable KDS and Table Management

-- 1. Kitchen Tickets (Live Orders)
CREATE TABLE IF NOT EXISTS kitchen_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id UUID REFERENCES branches(id),
  table_number TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING', -- PENDING, COMPLETED, VOIDED
  items JSONB DEFAULT '[]'::jsonb, -- Array of objects { name, qty, status, notes }
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- 2. Dining Tables (Floor Plan status)
CREATE TABLE IF NOT EXISTS dining_tables (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  branch_id UUID REFERENCES branches(id),
  table_number TEXT NOT NULL,
  capacity INTEGER DEFAULT 4,
  status TEXT DEFAULT 'AVAILABLE', -- AVAILABLE, OCCUPIED, RESERVED, DIRTY
  current_order_id UUID, -- distinct from completed orders
  x_position INTEGER DEFAULT 0,
  y_position INTEGER DEFAULT 0
);

-- 3. Persistent Cart Items (Pre-order / Tab)
CREATE TABLE IF NOT EXISTS table_cart_items (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  branch_id UUID REFERENCES branches(id),
  table_number TEXT NOT NULL,
  variant_id UUID REFERENCES variants(id),
  product_name TEXT NOT NULL,
  price_at_addition INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  modifiers JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'DRAFT', -- DRAFT (local), SENT (kitchen), SERVED
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Settings for Store Configuration (if not exists)
CREATE TABLE IF NOT EXISTS settings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB NOT NULL
);

-- Seed some default settings
INSERT INTO settings (key, value) VALUES
('dining_mode', 'false'::jsonb),
('kitchen_display_active', 'true'::jsonb),
('store_name', '"OpenTill POS"'::jsonb),
('tax_rate', '10'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Seed some tables
INSERT INTO dining_tables (table_number, capacity, x_position, y_position) VALUES
('1', 4, 10, 10),
('2', 2, 60, 10),
('3', 6, 10, 60),
('4', 4, 60, 60)
ON CONFLICT DO NOTHING;
